# Generated by Django 4.2.2 on 2023-07-03 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateField(default=datetime.date(2023, 7, 2), verbose_name='Fecha de registro')),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
    ]
